name: meme
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2 # Updated to match common usage with Flutter
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  share_plus: ^10.0.2
  path_provider: ^2.0.11 # Added this line
  carousel_slider: ^5.0.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true





